CREATE TABLE LTM_TASK 
(
  ID NUMBER NOT NULL 
, TASK_ID VARCHAR2(50 BYTE) 
, FIRST_NAME VARCHAR2(50 BYTE) 
, LAST_NAME VARCHAR2(50 BYTE) 
, TITLE VARCHAR2(50 BYTE) 
, CHILD1 VARCHAR2(50 BYTE) 
, CHILD2 VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
